#!/usr/bin/env bash
#
# Bootstrap a local Altair demo in one command.
#
# Requirements:
#   - Docker  (https://docs.docker.com/engine/install/)
#   - Supabase CLI  (https://supabase.com/docs/guides/cli)
#
# What this does:
#   1. Runs `supabase start` (spins up local Postgres, Auth, Realtime, Studio)
#   2. Applies supabase/schema.sql (the full consolidated schema)
#   3. Applies supabase/revenue_engine.sql
#   4. Seeds the rich demo dataset (supabase/seed.sql)
#   5. Creates a demo admin user (demo@example.com / demo-password-1234)
#   6. Writes .env.local with the local Supabase anon key + URL
#
# Usage:
#   ./scripts/bootstrap-local.sh            # bootstrap from scratch
#   ./scripts/bootstrap-local.sh --reset    # wipe DB and re-seed
#
# Safe to re-run: the seed uses ON CONFLICT DO NOTHING on every insert.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RESET=false
for arg in "$@"; do
  case "$arg" in
    --reset) RESET=true ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# --- 1. pre-flight ---------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "❌ docker not found. Install Docker first: https://docs.docker.com/engine/install/"
  exit 1
fi
if ! command -v supabase >/dev/null 2>&1; then
  echo "❌ supabase CLI not found. Install it: https://supabase.com/docs/guides/cli"
  exit 1
fi

# --- 2. start Supabase local stack ----------------------------------------
echo "▶ Starting Supabase local stack (this takes ~30s the first time)..."
if $RESET; then
  supabase stop --no-backup >/dev/null 2>&1 || true
fi
supabase start

# --- 3. locate the Postgres container -------------------------------------
DB_CONTAINER="$(docker ps --format '{{.Names}}' | grep -E '^supabase_db_' | head -n1 || true)"
if [ -z "$DB_CONTAINER" ]; then
  echo "❌ Could not find supabase_db_* container. Try: supabase start"
  exit 1
fi

run_sql_file() {
  docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q < "$1"
}

# --- 4. apply schema + revenue engine + seed -----------------------------
echo "▶ Applying schema.sql..."
run_sql_file supabase/schema.sql

echo "▶ Applying revenue_engine.sql..."
run_sql_file supabase/revenue_engine.sql

echo "▶ Seeding demo data..."
run_sql_file supabase/seed.sql

# --- 6. create demo admin via Auth admin API ------------------------------
echo "▶ Creating demo admin user..."
SUPABASE_STATUS="$(supabase status -o env)"
eval "$SUPABASE_STATUS"
: "${API_URL:?supabase status did not return API_URL}"
: "${SERVICE_ROLE_KEY:?supabase status did not return SERVICE_ROLE_KEY}"

# Create user (idempotent: returns 422 if user exists, which we ignore)
CREATE_RESP="$(curl -s -o /tmp/altair-demo-user.json -w '%{http_code}' \
  -X POST "$API_URL/auth/v1/admin/users" \
  -H "apikey: $SERVICE_ROLE_KEY" \
  -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
  -H "Content-Type: application/json" \
  -d '{"email":"demo@example.com","password":"demo-password-1234","email_confirm":true}')"

case "$CREATE_RESP" in
  2*)       echo "  ▸ demo@example.com created" ;;
  422|409)  echo "  ▸ demo@example.com already exists" ;;
  *)        echo "  ⚠ user-create returned HTTP $CREATE_RESP:"; cat /tmp/altair-demo-user.json; echo ;;
esac

# Grant pmo_admin
docker exec -i "$DB_CONTAINER" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO public.user_roles (email, full_name, role)
VALUES ('demo@example.com', 'Demo Admin', 'pmo_admin')
ON CONFLICT (email) DO UPDATE SET role = 'pmo_admin';
SQL

# --- 7. write .env.local -------------------------------------------------
ENV_FILE="$ROOT/.env.local"
if [ ! -f "$ENV_FILE" ] || $RESET; then
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-local.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_URL=$API_URL
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
ALLOWED_ORIGINS=http://localhost:5173
ALTAIR_BASE_URL=http://localhost:5173
ALTAIR_EXTERNAL_API_KEY=local-demo-api-key-change-me
EOF
  echo "▶ Wrote .env.local with local Supabase keys"
fi

# --- 8. summary ----------------------------------------------------------
cat <<EOF

✅ Altair local demo is ready.

   Studio:     http://localhost:54323     (DB browser, auth, logs)
   API:        $API_URL
   DB:         postgresql://postgres:postgres@localhost:54322/postgres

   Demo login (DO NOT use this password anywhere public):
     Email:    demo@example.com
     Password: demo-password-1234

   Next steps:
     npm install
     npm run dev        →  open http://localhost:5173

   Tear down when done:
     supabase stop

EOF
